/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeedbapp;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author asoliman
 */
public class DBGUI extends javax.swing.JFrame {

    /**
     * Creates new form DBGUI
     */
    
    private DBmanger dbManger;
    
    public DBGUI() {
        initComponents();
        dbManger = new DBmanger();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        fnameTF = new javax.swing.JTextField();
        MnameTF = new javax.swing.JTextField();
        LnameTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        phoneTF = new javax.swing.JTextField();
        nextEmp = new javax.swing.JButton();
        firstEmp = new javax.swing.JButton();
        lastEmp = new javax.swing.JButton();
        delEmp = new javax.swing.JButton();
        updateEmp = new javax.swing.JButton();
        newEmp = new javax.swing.JButton();
        prevEmp = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("First name: ");

        jLabel3.setText("Middle name: ");

        jLabel4.setText("Last name: ");

        jLabel5.setText("Email:");

        jLabel6.setText("phone:");

        idTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTFActionPerformed(evt);
            }
        });

        MnameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnameTFActionPerformed(evt);
            }
        });

        nextEmp.setText("NEXT");
        nextEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextEmpActionPerformed(evt);
            }
        });

        firstEmp.setText("FIRST");
        firstEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstEmpActionPerformed(evt);
            }
        });

        lastEmp.setText("LAST");
        lastEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastEmpActionPerformed(evt);
            }
        });

        delEmp.setText("DELETE");
        delEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delEmpActionPerformed(evt);
            }
        });

        updateEmp.setText("UPDATE");
        updateEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmpActionPerformed(evt);
            }
        });

        newEmp.setText("NEW");
        newEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmpActionPerformed(evt);
            }
        });

        prevEmp.setText("PREVIOUS");
        prevEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevEmpActionPerformed(evt);
            }
        });

        clearBtn.setText("CLEAR");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(delEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(firstEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nextEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prevEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LnameTF)
                            .addComponent(emailTF)
                            .addComponent(phoneTF, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                            .addComponent(idTF)
                            .addComponent(fnameTF)
                            .addComponent(MnameTF)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(newEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearBtn)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prevEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTFActionPerformed

    private void firstEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstEmpActionPerformed
        // TODO add your handling code here:
        
        Employee newEmpData = new Employee();
        
        try {
            newEmpData = dbManger.getFirstEmployee();
            idTF.setText(Integer.toString(newEmpData.getId()));
            fnameTF.setText(newEmpData.getFname());
            MnameTF.setText(newEmpData.getMname());
            LnameTF.setText(newEmpData.getLname());
            emailTF.setText(newEmpData.getEmail());
            phoneTF.setText(newEmpData.getPhone());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DBGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_firstEmpActionPerformed

    private void newEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmpActionPerformed
        // TODO add your handling code here:
        
        
        Employee newEmpData = new Employee();
        
        
        
        try {
            if(! (fnameTF.getText().isEmpty() && MnameTF.getText().isEmpty() && LnameTF.getText().isEmpty() && emailTF.getText().isEmpty() && phoneTF.getText().isEmpty())){
                newEmpData.setFname(fnameTF.getText());
                newEmpData.setMname(MnameTF.getText());
                newEmpData.setLname(LnameTF.getText());
                newEmpData.setEmail(emailTF.getText());
                newEmpData.setPhone(phoneTF.getText());
            
                dbManger.insertRow(newEmpData);
                clear();
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DBGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_newEmpActionPerformed

    private void MnameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnameTFActionPerformed

    private void updateEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmpActionPerformed
        // TODO add your handling code here:
        
        Employee newEmpData = new Employee();
        
        
            
            try {
                // All fields are not empty
                if(! (fnameTF.getText().isEmpty() && MnameTF.getText().isEmpty() && LnameTF.getText().isEmpty() && emailTF.getText().isEmpty() && phoneTF.getText().isEmpty())){
                    newEmpData.setId(Integer.parseInt(idTF.getText()));
                    newEmpData.setFname(fnameTF.getText());
                    newEmpData.setMname(MnameTF.getText());
                    newEmpData.setLname(LnameTF.getText());
                    newEmpData.setEmail(emailTF.getText());
                    newEmpData.setPhone(phoneTF.getText());
                    dbManger.updateRow(newEmpData);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(DBGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_updateEmpActionPerformed

    private void delEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delEmpActionPerformed
        // TODO add your handling code here: 
        Employee newEmpData = new Employee();
        
        
        newEmpData.setId(Integer.parseInt(idTF.getText()));
        newEmpData.setFname(fnameTF.getText());
        newEmpData.setMname(MnameTF.getText());
        newEmpData.setLname(LnameTF.getText());
        newEmpData.setEmail(emailTF.getText());
        newEmpData.setPhone(phoneTF.getText());
        
        
        try {
            dbManger.deleteRow(newEmpData);
            clear();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DBGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_delEmpActionPerformed

    private void lastEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastEmpActionPerformed
        // TODO add your handling code here:
        Employee newEmpData = new Employee();
        
        
        try {
            newEmpData = dbManger.getLastEmployee();
            idTF.setText(Integer.toString(newEmpData.getId()));
            fnameTF.setText(newEmpData.getFname());
            MnameTF.setText(newEmpData.getMname());
            LnameTF.setText(newEmpData.getLname());
            emailTF.setText(newEmpData.getEmail());
            phoneTF.setText(newEmpData.getPhone());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DBGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_lastEmpActionPerformed

    private void nextEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextEmpActionPerformed
        // TODO add your handling code here:
        
        Employee newEmpData = new Employee();
        
        
        newEmpData = dbManger.getNextEmployee();
        
        idTF.setText(Integer.toString(newEmpData.getId()));
        fnameTF.setText(newEmpData.getFname());
        MnameTF.setText(newEmpData.getMname());
        LnameTF.setText(newEmpData.getLname());
        emailTF.setText(newEmpData.getEmail());
        phoneTF.setText(newEmpData.getPhone());
    }//GEN-LAST:event_nextEmpActionPerformed

    private void prevEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevEmpActionPerformed
        // TODO add your handling code here:
        
        Employee newEmpData = new Employee();
        
        
        newEmpData = dbManger.getPrevEmployee();
        
        idTF.setText(Integer.toString(newEmpData.getId()));
        fnameTF.setText(newEmpData.getFname());
        MnameTF.setText(newEmpData.getMname());
        LnameTF.setText(newEmpData.getLname());
        emailTF.setText(newEmpData.getEmail());
        phoneTF.setText(newEmpData.getPhone());
    }//GEN-LAST:event_prevEmpActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBGUI().setVisible(true);
            }
        });
    }
    
    
    private void clear(){
        idTF.setText("");
        fnameTF.setText("");
        MnameTF.setText("");
        LnameTF.setText("");
        emailTF.setText("");
        phoneTF.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LnameTF;
    private javax.swing.JTextField MnameTF;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton delEmp;
    private javax.swing.JTextField emailTF;
    private javax.swing.JButton firstEmp;
    private javax.swing.JTextField fnameTF;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton lastEmp;
    private javax.swing.JButton newEmp;
    private javax.swing.JButton nextEmp;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JButton prevEmp;
    private javax.swing.JButton updateEmp;
    // End of variables declaration//GEN-END:variables
}
